ARG PHP_VERSION=8.3
FROM php:${PHP_VERSION}-apache

# Install system dependencies
RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    curl \
    git \
    netcat-traditional \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libicu-dev \
    apache2-utils \
    brotli \
    && apt-get install -y libapache2-mod-brotli || echo "Brotli module not available" \
    && rm -rf /var/lib/apt/lists/*

# Configure and install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
    mysqli \
    pdo_mysql \
    zip \
    gd \
    mbstring \
    xml \
    intl \
    opcache

# Install Redis extension
RUN pecl install redis && docker-php-ext-enable redis

# Copy module enablement script
COPY infrastructure/docker/enable-modules.sh /tmp/enable-modules.sh
COPY infrastructure/docker/check-modules.sh /usr/local/bin/check-modules.sh
COPY infrastructure/docker/verify-build.sh /tmp/verify-build.sh
RUN chmod +x /tmp/enable-modules.sh && /tmp/enable-modules.sh && rm /tmp/enable-modules.sh \
    && chmod +x /usr/local/bin/check-modules.sh \
    && chmod +x /tmp/verify-build.sh

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer

# Base OPcache + JIT defaults (env-specific overrides in entrypoint)
RUN { \
    echo 'opcache.enable=1'; \
    echo 'opcache.enable_cli=1'; \
    echo 'opcache.jit_buffer_size=128M'; \
    echo 'opcache.jit=1255'; \
    echo 'opcache.memory_consumption=256'; \
    echo 'opcache.interned_strings_buffer=32'; \
    echo 'opcache.max_accelerated_files=20000'; \
    echo 'opcache.revalidate_freq=1'; \
    echo 'opcache.validate_timestamps=1'; \
    echo 'opcache.fast_shutdown=1'; \
    echo 'realpath_cache_size=4096K'; \
    echo 'realpath_cache_ttl=600'; \
} >> /usr/local/etc/php/conf.d/opcache.ini

# Set recommended PHP settings
RUN echo "upload_max_filesize=100M" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "post_max_size=100M" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "memory_limit=512M" >> /usr/local/etc/php/conf.d/memory.ini \
    && echo "max_execution_time=300" >> /usr/local/etc/php/conf.d/execution.ini

# Copy Apache configurations and entrypoint
COPY infrastructure/docker/apache-vhost.conf /etc/apache2/sites-available/000-default.conf
COPY infrastructure/docker/apache-production.conf /etc/apache2/sites-available/001-production.conf
COPY infrastructure/docker/apache-subdomain.conf /etc/apache2/sites-available/002-subdomain.conf
COPY infrastructure/docker/performance.conf /etc/apache2/conf-available/performance.conf
COPY infrastructure/docker/entrypoint.sh /usr/local/bin/entrypoint.sh

# Enable performance configuration and set entrypoint permissions
RUN a2enconf performance && chmod +x /usr/local/bin/entrypoint.sh

# Set working directory
WORKDIR /var/www/html

# Copy composer files first for better layer caching
COPY composer.json composer.lock ./

# Install dependencies
RUN composer install --no-scripts --no-autoloader --no-dev --prefer-dist

# Create directory structure for bind mount
RUN mkdir -p /var/www/html/public /var/www/html/common/Migrations /var/www/html/modules \
    && echo "<?php // Placeholder for bind mount ?>" > /var/www/html/preload.php

# Note: Autoloader will be generated by entrypoint when bind mount is active

# Set proper permissions for bind mount
RUN chown -R www-data:www-data /var/www/html

# Expose port 80
EXPOSE 80

# Use custom entrypoint for initialization
CMD ["/usr/local/bin/entrypoint.sh"]