# Production Docker Compose Configuration
# Usage: docker-compose -f infrastructure/docker-compose.production.yaml up -d
# This is a standalone production configuration (does not extend development config)

# Production Docker Compose Configuration
# Expects .env file in the same directory (infrastructure/.env)
# Generate with: ./infrastructure/scripts/run.sh sync-config
# See infrastructure/docs/PRODUCTION-DEPLOYMENT.md for complete guide

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.6
    container_name: proto-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?Please set DB_ROOT_PASSWORD in infrastructure/.env file}
      MARIADB_DATABASE: ${DB_DATABASE:-proto}
      MARIADB_USER: ${DB_USERNAME:-proto_app_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:?Please set DB_PASSWORD in infrastructure/.env file}
      MARIADB_AUTO_UPGRADE: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./infrastructure/config/mariadb/conf.d:/etc/mysql/mariadb.conf.d:ro
    networks:
      - proto-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max_connections=5000
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: proto-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
      - ./infrastructure/config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - proto-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:?Please set REDIS_PASSWORD in infrastructure/.env file}
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # PHP Apache Web Server - PRODUCTION with baked-in assets
  web:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile
    image: proto-project-web:latest
    container_name: proto-web
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS/HTTP2
    # PRODUCTION: Only mount writable directories, NOT code
    # All PHP code and built frontend apps are baked into the image
    volumes:
      # Writable directories for uploads/attachments
      - ./public/files:/var/www/html/public/files:rw
      - ./common/files:/var/www/html/common/files:rw
      # Configuration files (optional - can be baked into image too)
      - ./infrastructure/docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./infrastructure/docker/apache-mpm.conf:/etc/apache2/conf-available/mpm-tuning.conf:ro
    depends_on:
      - mariadb
      - redis
    networks:
      - proto-network
    environment:
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-proto}
      - DB_USERNAME=${DB_USERNAME:-proto_app_user}
      - DB_PASSWORD=${DB_PASSWORD:-ProtoApp2025!SecureDbPass#789}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-ProtoRedis2025!CacheSecure#123456789}
      - APP_ENV=production
      - AUTO_MIGRATE=true
      - DOCKER_CONTAINER=true
      - PROJECT_ROOT=/var/www/html
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@proto-project.local}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Proto Project}
      - MAIL_ENABLED=${MAIL_ENABLED:-true}
      - CORS_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health.php >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

networks:
  proto-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
